### ISSUE TITLE
To-Do

### ISSUE THREAD

**Issue by manderio** [manderio/WindowsTools#2]
List of things to do for the project, if you have a feature request, file an issue, don't add it here. Thank you!

**Comment by manderio** [comment]
## Init-Module - functions
Classes:
- [ ] Variables: Complete all variables for the script
- [ ] ErrorMessages: Add relevant error messages with text for try/catch
- [ ] Defaults: Set up a fetch of defaults from config file using json

Psudo:
- [ ] Testing
- [ ] Correct the Class
- [ ] Add Try/Catch error handling

VersionSwitch:
- [ ] Exit shortcut
- [ ] Info command
- [ ] Multi command support
- [ ] Single command support
- [ ] Prompt edit

ConnectionSetup:
- [ ] Check remote host for already created connection profile
- [ ] Replacement of profile
- [ ] Guided setup
- [ ] Quick setup

Additional functionality:
- [ ] Add a config command for the Defaults class
- [ ] Add settings folder
